export const documentTypes = {
  START_FETCH: "START_FETCH_DOCUMENT",
  UPDATE_SUCCESS: "UPDATE_DOCUMENT_SUCCESS",
  FETCH_FAIL: "FETCH_FETCH_DOCUMENT_FAIL",
  RESET_MESSAGE: "RESET_MESSAGE_DOCUMENT",
};
