export const listDocumentTypes = {
  START_FETCH: "START_FETCH_LIST_DOCUMENT",
  FETCH_SUCCESS: "FETCH_LIST_DOCUMENT_SUCCESS",
  FETCH_FAIL: "FETCH_LIST_DOCUMENT_FAIL",
  RESET_MESSAGE: "RESET_MESSAGE_LIST_DOCUMENT",
};
